# https://github.com/itzg/docker-minecraft-server
services:
  mc:
    image: itzg/minecraft-server:java21
    container_name: modded-mc
    tty: true
    stdin_open: true
    environment:
      TYPE: "FTBA"
      FTB_MODPACK_ID: "125"
      MEMORY: "12G"
      MOTD: "Modded Minecraft"
      EULA: "TRUE"
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
    restart: on-failure
    networks:
      - alexjs_network

networks:
  alexjs_network:
